defaults: &defaults
    docker:
        - image: circleci/node:12.10.0

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - run: 
                name: Install Dependence
                command: |
                    sudo npm install -g gatsby-cli && yarn install && gatsby build
            - save_cache:
                key: meme-v1-{{ checksum "package.json" }}
                paths:
                    - "public"

    deploy:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Update System
                command: |
                    sudo apt-get update && sudo apt-get install rsync
            - restore_cache:
                keys:
                    - meme-v1-{{ checksum "package.json" }}
            - deploy:
                name: Deploy via ssh
                command: |
                    mkdir -p ~/.ssh
                    touch ~/.ssh/known_hosts
                    { ssh-keyscan $SSH_IP 2> /dev/null; } >> ~/.ssh/known_hosts
                    if [ ${CIRCLE_BRANCH} = "master" ];then
                        echo "Circle CI do not support id_25519 pubkey"
                        # rsync -az -v --delete -e ssh public/* $SSH_USER@$SSH_IP:/data/www/meme/
                    else
                        echo "Not master branch"
                    fi

workflows:
    version: 2

    Meme-CI:
        jobs:
            - build
            - deploy:
                requires:
                    - build
